(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
(*
This is the CoMMfoc package. For the notebook that generated this package file and additional documentaion, see https://github.com/CoMMfoc/CoMMfoc
*)


(* ::Input::Initialization:: *)
BeginPackage["CoMMfoc`"];


(* ::Input::Initialization:: *)
$CoMMfocVersion::usage="$CoMMfocVersion prints the current version of the RB-SFA package in use and its timestamp.";
$CoMMfocTimestamp::usage="$CoMMfocTimestamp prints the timestamp of the current version of the RB-SFA package.";
Begin["`Private`"];
$CoMMfocVersion:="CoMMfoc v0.1, "<>$CoMMfoctimestamp;
End[];


(* ::Input::Initialization:: *)
Begin["`Private`"];
$CoMMfocTimestamp="Wed 23 Sep 2020 17:24:38";
End[];


(* ::Input::Initialization:: *)
$CoMMfocDirectory::usage="$CoMMfocDirectory is the directory where the current RB-SFA package instance is located.";


(* ::Input::Initialization:: *)
Begin["`Private`"];
With[{softLinkTestString=StringSplit[StringJoin[ReadList["! ls -la "<>StringReplace[$InputFileName,{" "->"\\ "}],String]]," -> "]},
If[Length[softLinkTestString]>1,(*Testing in case $InputFileName is a soft link to the actual directory.*)
$CoMMfocDirectory=StringReplace[DirectoryName[softLinkTestString[[2]]],{" "->"\\ "}],
$CoMMfocDirectory=StringReplace[DirectoryName[$InputFileName],{" "->"\\ "}];
]];
End[];


(* ::Input::Initialization:: *)
$CoMMfocCommit::usage="$CoMMfocCommit returns the git commit log at the location of the RB-SFA package if there is one.";
$CoMMfocCommit::OS="$CoMMfocCommit has only been tested on Linux.";


(* ::Input::Initialization:: *)
Begin["`Private`"];
$CoMMfocCommit:=(If[$OperatingSystem!="Unix",Message[$CoMMfocCommit::OS]];
StringJoin[Riffle[ReadList["!cd "<>$CoMMfocDirectory<>" && git log -1",String],{"\n"}]]);
End[];


(* ::Input::Initialization:: *)
EndPackage[];


(* ::Input::Initialization:: *)
DistributeDefinitions["CoMMfoc`"];
